name: Build

on:
  push:
    branches: [ main ]
    <<: &ci_paths
      paths-ignore:
        - 'deps/**'
      paths:
        - 'src/**'
        - 'include/**'
        - '**/*.cmake'
        - 'CMakeLists.txt'
        - '**/CMakeLists.txt'
        - '.gitmodules'
        - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    <<: *ci_paths
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y \
          gcc-14 g++-14 \
          cmake \
          ninja-build \
          pandoc \
          libasound2-dev \
          libjack-jackd2-dev \
          ladspa-sdk \
          libcurl4-openssl-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libx11-dev \
          libxcomposite-dev \
          libxcursor-dev \
          libxext-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxrender-dev \
          libglu1-mesa-dev \
          mesa-common-dev

    - name: Setup Boost
      id: install-boost
      uses: MarkusJx/install-boost@v2
      with:
        boost_version: 1.89.0
        platform_version: 24.04
        toolset: gcc

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja \
        -DCMAKE_C_COMPILER=gcc-14 \
        -DCMAKE_CXX_COMPILER=g++-14 \
        -DCMAKE_BUILD_TYPE=Release \
        -DELEMENT_ENABLE_UPDATER=OFF \
        -DELEMENT_BUILD_PLUGINS=ON
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: element-ubuntu-latest
        path: |
          build/element_app_artefacts/Release/
          build/element_instrument_artefacts/Release/
          build/element_effect_artefacts/Release/
          build/element_midi_effect_artefacts/Release/
